# 02_qualitative_coding_ecw_grantees.ipynb 


In [2]:
import pandas as pd

segments = [
    # National
    {
        "id": "N1",
        "level": "national",
        "text": "Cyclone Freddy affected 16 local authority areas, all located in Malawi’s Southern Region.",
        "codes": "TYPE_IMPACT; DOM_COORD_SYSTEMS; ECW_ACCESS",
    },
    {
        "id": "N2",
        "level": "national",
        "text": "Nationally, 633 education institutions were affected, including 550 primary schools, 74 secondary schools, 3 colleges and 6 universities.",
        "codes": "TYPE_IMPACT; DOM_ACCESS; DOM_INFRA_WASH; ECW_ACCESS",
    },
    {
        "id": "N3",
        "level": "national",
        "text": "Across these institutions, 72 classrooms were fully destroyed and 460 classrooms were partially destroyed.",
        "codes": "TYPE_IMPACT; DOM_INFRA_WASH; ECW_ACCESS; ECW_PROTECTION",
    },
    {
        "id": "N4",
        "level": "national",
        "text": "A total of 408 schools were used as IDP camps, with 1,481 classrooms occupied by displaced populations.",
        "codes": "TYPE_IMPACT; DOM_ACCESS; DOM_INFRA_WASH; DOM_PSS_PROTECTION; ECW_ACCESS; ECW_PROTECTION; XCUT_IDP",
    },
    {
        "id": "N5",
        "level": "national",
        "text": "An estimated 724,709 learners, including 368,313 girls and 356,396 boys, were unable to access learning during the emergency.",
        "codes": "TYPE_IMPACT; DOM_ACCESS; ECW_ACCESS; ECW_EQUITY; XCUT_GENDER_GIRLS; XCUT_GENDER_BOYS",
    },
    {
        "id": "N6",
        "level": "national",
        "text": "In total, 978 teachers were affected nationally, including 302 female teachers.",
        "codes": "TYPE_IMPACT; DOM_TEACHERS; ECW_LEARNING; ECW_EQUITY; XCUT_GENDER_GIRLS",
    },
    {
        "id": "N7",
        "level": "national",
        "text": "Total effects on the education subsector were estimated at USD 42.09 million, including USD 30.2 million in physical damage to education infrastructure.",
        "codes": "TYPE_IMPACT; DOM_INFRA_WASH; DOM_COORD_SYSTEMS; ECW_ACCESS; ECW_LEARNING",
    },
    {
        "id": "N8",
        "level": "national",
        "text": "Sanitation facilities were heavily affected, with 986 toilets fully destroyed and 542 partially destroyed across affected schools.",
        "codes": "TYPE_IMPACT; DOM_INFRA_WASH; ECW_PROTECTION; ECW_ACCESS",
    },
    {
        "id": "N9",
        "level": "national",
        "text": "Learners in affected areas lost on average almost 25 academic days due to Cyclone Freddy.",
        "codes": "TYPE_IMPACT; DOM_LEARNING_QUALITY; DOM_ACCESS; ECW_LEARNING",
    },

    # Thyolo
    {
        "id": "T1",
        "level": "thyolo",
        "text": "In Thyolo District, 50 education institutions were affected, including 43 primary schools and 7 secondary schools.",
        "codes": "TYPE_IMPACT; DOM_ACCESS; DOM_INFRA_WASH; ECW_ACCESS; XCUT_THYOLO",
    },
    {
        "id": "T2",
        "level": "thyolo",
        "text": "Education subsector recovery needs in Thyolo were estimated at USD 1.78 million.",
        "codes": "TYPE_IMPACT; TYPE_GAP_NEED; DOM_INFRA_WASH; DOM_COORD_SYSTEMS; ECW_ACCESS; ECW_LEARNING; XCUT_THYOLO",
    },
    {
        "id": "T3",
        "level": "thyolo",
        "text": "Across all sectors in Thyolo, total disaster effects were valued at USD 35.4 million, highlighting broader multi-sectoral vulnerability.",
        "codes": "TYPE_IMPACT; DOM_COORD_SYSTEMS; XCUT_THYOLO",
    },
    {
        "id": "T4",
        "level": "thyolo",
        "text": "As of 18 March 2023, Thyolo hosted 36 IDP camps sheltering 835 displaced households and 3,759 displaced people.",
        "codes": "TYPE_IMPACT; DOM_ACCESS; DOM_PSS_PROTECTION; ECW_PROTECTION; XCUT_IDP; XCUT_THYOLO",
    },
    {
        "id": "T5",
        "level": "thyolo",
        "text": "Cyclone Freddy caused 13 deaths, 65 injuries and no reported missing persons in Thyolo.",
        "codes": "TYPE_IMPACT; DOM_PSS_PROTECTION; ECW_PROTECTION; XCUT_THYOLO",
    },
    {
        "id": "T6",
        "level": "thyolo",
        "text": "Road access to camps in Thyolo was severely disrupted, with all roads to camps reported inaccessible, the Makwasa road cut off, and the Suwadzi and Nawasadi bridges collapsed.",
        "codes": "TYPE_IMPACT; DOM_ACCESS; DOM_COORD_SYSTEMS; ECW_ACCESS; XCUT_THYOLO; XCUT_RURAL",
    },
    {
        "id": "T7",
        "level": "thyolo",
        "text": "An early situation report dated 14 March 2023 stated that no damage to schools in Thyolo had been recorded so far, but this was later superseded by verified data confirming significant education damage.",
        "codes": "TYPE_IMPACT; TYPE_ENABLER_BARRIER; DOM_COORD_SYSTEMS; XCUT_THYOLO",
    },
    {
        "id": "T8",
        "level": "thyolo",
        "text": "Given its 50 affected schools and USD 1.78 million in education recovery needs, Thyolo is classified as a moderately-to-highly affected district and warrants scaled Education in Emergencies interventions comparable to districts like Chiradzulu, Blantyre and Zomba.",
        "codes": "TYPE_GAP_NEED; TYPE_LESSON_RECOMMENDATION; DOM_ACCESS; DOM_INFRA_WASH; DOM_PSS_PROTECTION; ECW_ACCESS; ECW_PROTECTION; XCUT_THYOLO; XCUT_OTHER_DISTRICTS",
    },
]

qual_df = pd.DataFrame(segments)
qual_df

id     level                                               text  \
0   N1  national  Cyclone Freddy affected 16 local authority are...   
1   N2  national  Nationally, 633 education institutions were af...   
2   N3  national  Across these institutions, 72 classrooms were ...   
3   N4  national  A total of 408 schools were used as IDP camps,...   
4   N5  national  An estimated 724,709 learners, including 368,3...   
5   N6  national  In total, 978 teachers were affected nationall...   
6   N7  national  Total effects on the education subsector were ...   
7   N8  national  Sanitation facilities were heavily affected, w...   
8   N9  national  Learners in affected areas lost on average alm...   
9   T1    thyolo  In Thyolo District, 50 education institutions ...   
10  T2    thyolo  Education subsector recovery needs in Thyolo w...   
11  T3    thyolo  Across all sectors in Thyolo, total disaster e...   
12  T4    thyolo  As of 18 March 2023, Thyolo hosted 36 IDP camp...   
13  T5    thyolo  Cyclone Freddy caused 13 deaths, 65 injuries a...   
14  T6    thyolo  Road access to camps in Thyolo was severely di...   
15  T7    thyolo  An early situation report dated 14 March 2023 ...   
16  T8    thyolo  Given its 50 affected schools and USD 1.78 mil...   

                                                codes  
0          TYPE_IMPACT; DOM_COORD_SYSTEMS; ECW_ACCESS  
1   TYPE_IMPACT; DOM_ACCESS; DOM_INFRA_WASH; ECW_A...  
2   TYPE_IMPACT; DOM_INFRA_WASH; ECW_ACCESS; ECW_P...  
3   TYPE_IMPACT; DOM_ACCESS; DOM_INFRA_WASH; DOM_P...  
4   TYPE_IMPACT; DOM_ACCESS; ECW_ACCESS; ECW_EQUIT...  
5   TYPE_IMPACT; DOM_TEACHERS; ECW_LEARNING; ECW_E...  
6   TYPE_IMPACT; DOM_INFRA_WASH; DOM_COORD_SYSTEMS...  
7   TYPE_IMPACT; DOM_INFRA_WASH; ECW_PROTECTION; E...  
8   TYPE_IMPACT; DOM_LEARNING_QUALITY; DOM_ACCESS;...  
9   TYPE_IMPACT; DOM_ACCESS; DOM_INFRA_WASH; ECW_A...  
10  TYPE_IMPACT; TYPE_GAP_NEED; DOM_INFRA_WASH; DO...  
11        TYPE_IMPACT; DOM_COORD_SYSTEMS; XCUT_THYOLO  
12  TYPE_IMPACT; DOM_ACCESS; DOM_PSS_PROTECTION; E...  
13  TYPE_IMPACT; DOM_PSS_PROTECTION; ECW_PROTECTIO...  
14  TYPE_IMPACT; DOM_ACCESS; DOM_COORD_SYSTEMS; EC...  
15  TYPE_IMPACT; TYPE_ENABLER_BARRIER; DOM_COORD_S...  
16  TYPE_GAP_NEED; TYPE_LESSON_RECOMMENDATION; DOM...

# ECW Qualitative Coded Segments – Cyclone Freddy EiE (National + Thyolo)

These text passages are narrative restatements of the **national** and **Thyolo** Cyclone Freddy education impact data. Each passage is followed by the qualitative codes applied, based on the project codebook (TYPE_, DOM_, ECW_, XCUT_).

---

## 1. National-Level Segments

### N1 – Geographic scope

**Text passage**

Cyclone Freddy affected 16 local authority areas, all located in Malawi’s Southern Region.

**Codes**

- TYPE_IMPACT – Describes the overall scale and location of impact.
- DOM_COORD_SYSTEMS – Relates to the geographic extent and systems affected.
- ECW_ACCESS – Context for access and service disruption.

---

### N2 – Institutions affected

**Text passage**

Nationally, 633 education institutions were affected, including 550 primary schools, 74 secondary schools, 3 colleges and 6 universities.

**Codes**

- TYPE_IMPACT – Scope of damage to the education system.
- DOM_ACCESS – Availability of learning spaces.
- DOM_INFRA_WASH – Educational infrastructure affected.
- ECW_ACCESS – Impact on access to education.

---

### N3 – Classroom destruction

**Text passage**

Across these institutions, 72 classrooms were fully destroyed and 460 classrooms were partially destroyed.

**Codes**

- TYPE_IMPACT – Direct physical impact.
- DOM_INFRA_WASH – Structural damage to learning spaces.
- ECW_ACCESS – Barriers to accessing learning due to damage.
- ECW_PROTECTION – Safety concerns related to damaged structures.

---

### N4 – Schools used as IDP camps

**Text passage**

A total of 408 schools were used as IDP camps, with 1,481 classrooms occupied by displaced populations.

**Codes**

- TYPE_IMPACT – Disruption to the education system.
- DOM_ACCESS – Learning disrupted by use of schools as shelters.
- DOM_INFRA_WASH – Pressure on facilities used by both learners and IDPs.
- DOM_PSS_PROTECTION – Protection and wellbeing implications for children.
- ECW_ACCESS – Reduced access to learning spaces.
- ECW_PROTECTION – Protection risks linked to displacement.
- XCUT_IDP – Focus on internally displaced populations.

---

### N5 – Learners unable to access learning

**Text passage**

An estimated 724,709 learners, including 368,313 girls and 356,396 boys, were unable to access learning during the emergency.

**Codes**

- TYPE_IMPACT – Scale of impact on learners.
- DOM_ACCESS – Access to education disrupted.
- ECW_ACCESS – Core access outcome affected.
- ECW_EQUITY – Gender‑disaggregated impact.
- XCUT_GENDER_GIRLS – Specific reference to girls.
- XCUT_GENDER_BOYS – Specific reference to boys.

---

### N6 – Teachers affected

**Text passage**

In total, 978 teachers were affected nationally, including 302 female teachers.

**Codes**

- TYPE_IMPACT – Impact on education personnel.
- DOM_TEACHERS – Teachers’ status and wellbeing.
- ECW_LEARNING – Implications for teaching and learning continuity.
- ECW_EQUITY – Gender dimension among teachers.
- XCUT_GENDER_GIRLS – Specific reference to female teachers.

---

### N7 – Financial effects on the education sector

**Text passage**

Total effects on the education subsector were estimated at USD 42.09 million, including USD 30.2 million in physical damage to education infrastructure.

**Codes**

- TYPE_IMPACT – Financial scale of the disaster.
- DOM_INFRA_WASH – Damage to education infrastructure.
- DOM_COORD_SYSTEMS – Sector‑level assessment and planning implications.
- ECW_ACCESS – Resources needed to restore access.
- ECW_LEARNING – Investment required for learning continuity.

---

### N8 – Sanitation facilities damaged

**Text passage**

Sanitation facilities were heavily affected, with 986 toilets fully destroyed and 542 partially destroyed across affected schools.

**Codes**

- TYPE_IMPACT – Impact on WASH in schools.
- DOM_INFRA_WASH – WASH infrastructure damage.
- ECW_PROTECTION – Safe, dignified use of sanitation for learners.
- ECW_ACCESS – WASH as a condition for safe school access.

---

### N9 – Lost learning time

**Text passage**

Learners in affected areas lost on average almost 25 academic days due to Cyclone Freddy.

**Codes**

- TYPE_IMPACT – Duration of disruption.
- DOM_LEARNING_QUALITY – Learning loss and reduced instructional time.
- DOM_ACCESS – Time out of school.
- ECW_LEARNING – Negative impact on learning outcomes.

---

## 2. Thyolo District Segments

### T1 – Institutions affected in Thyolo

**Text passage**

In Thyolo District, 50 education institutions were affected, including 43 primary schools and 7 secondary schools.

**Codes**

- TYPE_IMPACT – Scale of impact at district level.
- DOM_ACCESS – Availability of learning spaces in Thyolo.
- DOM_INFRA_WASH – Damage to school infrastructure.
- ECW_ACCESS – District‑level access to education.
- XCUT_THYOLO – Specific focus on Thyolo.

---

### T2 – Education recovery needs in Thyolo

**Text passage**

Education subsector recovery needs in Thyolo were estimated at USD 1.78 million.

**Codes**

- TYPE_IMPACT – Monetary reflection of damage.
- TYPE_GAP_NEED – Expresses the recovery need.
- DOM_INFRA_WASH – Primarily infrastructure and facility restoration.
- DOM_COORD_SYSTEMS – Planning and budgeting implications.
- ECW_ACCESS – Resources needed to restore access.
- ECW_LEARNING – Resources needed to support learning recovery.
- XCUT_THYOLO – Thyolo‑specific.

---

### T3 – Total multi-sector disaster effects in Thyolo

**Text passage**

Across all sectors in Thyolo, total disaster effects were valued at USD 35.4 million, highlighting broader multi‑sectoral vulnerability.

**Codes**

- TYPE_IMPACT – Overall severity of the disaster in Thyolo.
- DOM_COORD_SYSTEMS – Multi‑sector assessment and systems perspective.
- XCUT_THYOLO – Thyolo‑specific vulnerability.

---

### T4 – Displacement and IDP camps in Thyolo

**Text passage**

As of 18 March 2023, Thyolo hosted 36 IDP camps sheltering 835 displaced households and 3,759 displaced people.

**Codes**

- TYPE_IMPACT – Scale of displacement.
- DOM_ACCESS – Potential disruption of schooling for displaced learners.
- DOM_PSS_PROTECTION – Protection and psychosocial concerns among IDPs.
- ECW_PROTECTION – Protection outcome at stake.
- XCUT_IDP – Focus on IDPs and camps.
- XCUT_THYOLO – Thyolo context.

---

### T5 – Human impact in Thyolo

**Text passage**

Cyclone Freddy caused 13 deaths, 65 injuries and no reported missing persons in Thyolo.

**Codes**

- TYPE_IMPACT – Direct human impact.
- DOM_PSS_PROTECTION – Trauma, bereavement, and safety implications.
- ECW_PROTECTION – Protection and wellbeing considerations.
- XCUT_THYOLO – Thyolo‑specific.

---

### T6 – Road access and infrastructure in Thyolo

**Text passage**

Road access to camps in Thyolo was severely disrupted, with all roads to camps reported inaccessible, the Makwasa road cut off, and the Suwadzi and Nawasadi bridges collapsed.

**Codes**

- TYPE_IMPACT – Physical access constraints.
- DOM_ACCESS – Access to schools and services hindered.
- DOM_COORD_SYSTEMS – Logistics, response and service delivery constraints.
- ECW_ACCESS – Impact on children’s ability to reach learning spaces.
- XCUT_THYOLO – Thyolo‑specific.
- XCUT_RURAL – Rural/remote access challenges.

---

### T7 – Data evolution and initial under‑reporting

**Text passage**

An early situation report dated 14 March 2023 stated that no damage to schools in Thyolo had been recorded so far, but this was later superseded by verified data confirming significant education damage.

**Codes**

- TYPE_IMPACT – Confirms that there was, in fact, education damage.
- TYPE_ENABLER_BARRIER – Illustrates limitations in early information and reporting.
- DOM_COORD_SYSTEMS – Data quality, assessment, and information management systems.
- XCUT_THYOLO – Thyolo‑specific reporting issue.

---

### T8 – Positioning of Thyolo within national response

**Text passage**

Given its 50 affected schools and USD 1.78 million in education recovery needs, Thyolo is classified as a moderately‑to‑highly affected district and warrants scaled Education in Emergencies interventions comparable to districts like Chiradzulu, Blantyre and Zomba.

**Codes**

- TYPE_GAP_NEED – Stated need for significant support.
- TYPE_LESSON_RECOMMENDATION – Implicit recommendation for prioritisation.
- DOM_ACCESS – Need to restore and maintain access to education.
- DOM_INFRA_WASH – Need to repair/rebuild school infrastructure.
- DOM_PSS_PROTECTION – Need for safe, protective learning environments.
- ECW_ACCESS – Justification for EiE access interventions.
- ECW_PROTECTION – Justification for protection‑related EiE support.
- XCUT_THYOLO – Focus on Thyolo.
- XCUT_OTHER_DISTRICTS – Comparison with other affected districts.